### ISSUE TITLE
Events without a CFP date link to 404

### ISSUE THREAD

**Issue by john-sandall** [JesperDramsch/python-deadlines#14]
2024 conferences without published CFP dates link to https://pythondeadlin.es/404.html

It could be nice to show a similar page to others with the map and twitter?

**Comment by john-sandall** [comment]
Sorry for multiple issues, had some network issues. Let me know if you want me to have a crack at this.

**Comment by JesperDramsch** [comment]
Argh! Haha, that's what I get for playing around with filters. 

Just needs to render and the pages are back!

I got a bit annoyed by the amount of TBAs on the main page, but it's probably best to just keep them.

**Comment by JesperDramsch** [comment]
Ok it's back: https://pythondeadlin.es/conference/pydata-london-2024/

Thanks for the heads up
