### ISSUE TITLE
Null events on the map

### ISSUE THREAD

**Issue by radujica** [JesperDramsch/python-deadlines#23]
<img width="175" alt="Screenshot 2024-04-22 at 20 21 50" src="https://github.com/JesperDramsch/python-deadlines/assets/8166962/7293fe73-894a-4120-b6f0-e61b088504bb">

Self-explanatory :)

**Comment by JesperDramsch** [comment]
Thanks for finding that @radujica. I'll try a fix in the coming days.

**Comment by JesperDramsch** [comment]
And fixed.  Thanks again

**Comment by JesperDramsch** [comment]
@all-contributors add @radujica for bug
